### ISSUE TITLE
Texture incompactibility with Greenfield texture pack

### ISSUE THREAD

**Issue by Tomhero200** [MisterJulsen/TrafficCraft#10]
**Version:**
 - Minecraft Version: All supported versions
 - Forge Version: All supported versions
 - Mod Version: --

**Describe the bug**
If the Greenfield texture pack is being used with this mod, the texture packs breaks the traffic light lights. They look like some kind of face with weird colors. Also the arrows and other icons don't work.

**To Reproduce**
1. Install the TrafficCraft mod.
2. Download the texture pack from the Greenfield texture pack download page.
3. Activate the texture pack.
4. Place a traffic light and turn it on. 

**Expected behavior**
The texture pack shouldn't break the traffic light textures.

**Screenshots**

**Additional context**

**Comment by MisterJulsen** [comment]
Some textures have been changed in the latest version. Please try whether the problem persists.
