### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by WaleonGames** [MisterJulsen/TrafficCraft#11]
#### Description:
When loading **TrafficCraft** on Minecraft 1.19.2, a NullPointerException error occurs related to the **Quark** mod (version 3.4-418). The TrafficCraft mod fails to load correctly due to an issue in the class `vazkii.quark.base.module.sync.SyncedFlagHandler`, where the `allFlags` field is null.

#### Steps to reproduce:
1. Run Minecraft 1.19.2 with Quark (v3.4-418) and TrafficCraft (v1.0.4-1.19.2).
2. The error occurs during the loading phase.

#### Expected behavior:
TrafficCraft mod should load without errors.

#### Console log (excerpt):
https://mclo.gs/T86ATJ8

#### Mod versions:
- **Minecraft**: 1.19.2
- **Quark**: 3.4-418
- **TrafficCraft**: 1.0.4-1.19.2
- **Java**: OpenJDK 17.0.11

#### Additional context:
It seems that the error is triggered by a conflict with the Quark mod's SyncedFlagHandler. Quark version 3.4-418 is known to interact with flags in a specific way, which could be causing this issue.

If any further details or full logs are needed, I would be happy to provide them.

**Comment by MisterJulsen** [comment]
This may be fixed in the latest version. Haven't tested it yet.

**Comment by WaleonGames** [comment]
The mod is working now, thank you very much
