### ISSUE TITLE
License please.

### ISSUE THREAD

**Issue by samuelh2005** [MisterJulsen/TrafficCraft#3]
**Is your feature request related to a problem? Please describe.**

More of a legal problem, without a license we may not be allowed to download / use your mod. A license will tell us what we are allowed to do with your code / mod.

**Describe the solution you'd like**

Adding a license of your choice to a file named `LICENSE` in the root of the repository, the file should have the full text of the license. (GitHub will "mark" the repository with the license and add an extra link to see the license, see the image below)

**Describe alternatives you've considered**

Nothing apart from finding a different mod.

**Additional context**

https://choosealicense.com/ may help you with this. I recommend the [MIT](https://choosealicense.com/licenses/mit/) or the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) 

![license](https://github.com/MisterJulsen/TrafficCraft/assets/41990982/ffa5af8d-5815-44bb-82d6-f0a5ba73ee7b)

**Comment by MisterJulsen** [comment]
Thank you very much for your hint! This is actually something I hadn't considered until now. But I understand what you mean, so I just changed that.
