### ISSUE TITLE
Cant edit Phase ID

### ISSUE THREAD

**Issue by ZEROX7** [MisterJulsen/TrafficCraft#5]
**Version:**
 - Minecraft Version: 1.20.1
 - Forge Version 47.2.20
 - Mod Version 1.0.1-1.220.1

**Describe the bug**
in the traffic light schedule editor you cant edit the numbers in the text field like seconds only changable via + or - buttons and phase id cant be edited at all

**Comment by MisterJulsen** [comment]
Thanks for the report! The problem should be fixed from version release 1.0.2. 👍
