### ISSUE TITLE
I hope to add Chinese language,

### ISSUE THREAD

**Issue by QianMuu** [MisterJulsen/TrafficCraft#8]
This is my simple translation into the Chinese language, but it's not perfect.
Hope you can add full Chinese language.
This mod is great.
[zh_cn.json](https://github.com/MisterJulsen/TrafficCraft/files/15045977/zh_cn.json)

**Comment by MisterJulsen** [comment]
Thank you very much for your contribution. I will look into adding it in the next update of TrafficCraft!
