### ISSUE TITLE
Asphalt invisible on Maps

### ISSUE THREAD

**Issue by MechtroYT** [MisterJulsen/TrafficCraft#9]
**Version:**
1.20.1
47.2.32
trafficcraft-1.0.4-1.20.1

**Describe the bug**
Asphalt is invisible on maps

**To Reproduce**
Create a map on a location where asphalt is

**Screenshots**
![2024-06-12_18 53 07](https://github.com/MisterJulsen/TrafficCraft/assets/112154206/1e10c2b4-b879-453b-8887-677434031a63)

**Comment by MisterJulsen** [comment]
Should be fixed in the latest version.
